version: '3'
services:
  app:
    image: sora62/sdc:app
    depends_on:
      - database
    ports:
      - '3000:3000'
    environment:
      - PGHOST=database
      - PGUSER=sara
      - PGPASSWORD=password
      - PGDATABASE=pgdb
      - PGPORT=5432
  database:
    image: sora62/sdc:db
    env_file:
      - .env
    ports:
      - '5432:5432'